import 'package:get/get.dart';
class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'en_US': {
          "J'ai participé au club d'informatique NMTC, et ma participation est en cours jusqu'à présent. Portant les valeurs de sérieux et d'apprentissage, j'ai la ferme volonté de traduire mes acquisitions en résultats concrets, tout ce qui intéresse un ingénieur en développement.": "I participated in the NMTC computer club, and my participation is ongoing so far. Bearing the values of seriousness and I have a strong desire to translate my Acquisitions in concrete results, anything that interests a Development engineer. ",
          "Téléphone : 20925959": "Phone: 20925959",
          "Gmail : Nawreselou2382@gmail.com": "Gmail : Nawreselou2382@gmail.com",
          "LinkedIn : linkedin.com/WearNawres": "LinkedIn : linkedin.com/WearNawres",
          "Langages Manipulés :": "Manipulated languages:",
          "c, PHP, JavaScript, java, c#, python, ARDUINO, SGBD, PHP, JavaFx, react, next js 13, express.js, Django, .Net, Spring Boot Dax (Power BI), Flutter (Dart), Angular": "c, PHP, JavaScript, java, c#, python, ARDUINO, SGBD, PHP, JavaFx, react, next js 13, express.js, Django, .Net, Spring Boot Dax (Power BI), Flutter (Dart), Angular",
          "Logiciels Utilisés :": "Software used:",
          "ISIS, CodeBlocks, Brackets, MATLAB, Visual Studio, Power BI Desktop, Eclipse, WampServer, Studio 3T, MongoDB, Intellij IDEA, XAMPP, Android Studio, STS": "ISIS, CodeBlocks, Brackets, MATLAB, Visual Studio, Power BI Desktop, Eclipse, WampServer, Studio 3T, MongoDB, Intellij IDEA, XAMPP, Android Studio, STS",
          "2023 - Spring Boot Certificate": "2023 - Certificat Spring Boot",
          "2022 - Azure Fundamentals certificate": "2022 - Certificat Azure Fundamentals",
          "2022 - Azure Devops certificate": "2022 - Certificat Azure Devops,",
          "2022 - Azure WebApps certificate": "2022 - Certificat Azure WebApps",
          "2022 - AI Services In Azure certificate": "2022 - Certificat AI Services In Azure",
          "2022 - Big Data certificate": "2022 - Certificat Big Data",
          "2022 - Power BI certificate": "2022 - Certificat Power BI",
          "2022 - Intelligence Artificial certificate": "2022 - Certificat Intelligence Artificial",
          "2023 - Automarketing certificate": "2023 - Certificat Automarketing",
          "2023 - planification stratégique certificate": "2023 - Certificat planification stratégique",
          "Adresse Professionnelle": "Business Address",
          "Paramétre": "setting",
          "Choisissez une langue": "Choose a language",
          "Expérience en Projets": "Project Experience",
          "Développement de projet E-Commerce": "E-Commerce Project Development",
          "Collaboration avec l\\'équipe de stagiaires de SwiftCode. Backend développé avec MongoDB et Node.js (Express.js). Frontend réalisé avec React.": "Collaboration with SwiftCode's team of interns. Backend developed with MongoDB and Node.js (Express.js). Frontend made with React.",
          "Développement du projet de santé Montale": "Development of the Montale Health Project",
          "Travail sur le backend avec Spring Boot, utilisation de STS, XAMPP, MySQL et Postman.": "Work on the backend with Spring Boot, using STS, XAMPP, MySQL and Postman.",
          "Développement de projet E-commerce": "E-commerce project development",
          "Backend développé avec MongoDB et Node.js (Express.js). Frontend réalisé avec Next.js": "Backend developed with MongoDB and Node.js (Express.js). Frontend made with Next.js",
          "Travail sur le backend et le frontend en utilisant Django.": "Work on the backend and frontend using Django.",
          "Développement de Site de société de photographie": "Project Development Photography Company Website",
          "Expérience professionnelle": "Professional experience",
          "Cheffe de Project IT": "IT Project Manager",
          "SwiftCode | Sfax | Juil. – 2023": "SwiftCode | Sfax | Juil. – 2023",
          "Stagiaire technicien OACA": "OACA Technician Trainee",
          "Sfax | Janv. - 2022": "Sfax | Janv. - 2022",
          "Observation des machines présentant un dysfonctionnement pour trouver la source du problème, diagnostiquant ainsi rapidement les causes de la panne pour réparation.": "Observation of malfunctioning machines to find the source of the problem, thus quickly diagnosing the causes of the failure for repair.",
          "Vérification du bon fonctionnement de Chaine Radio en prenant en charge les tests techniques et en corrigeant les problèmes rencontrés, assurant ainsi le bon déroulé de la production.": "Verification of the correct functioning of Radio Channel by taking charge of technical tests and correcting the problems encountered, thus ensuring the smooth running of production.",
          "Stagiaire technicien": "Trainee Technician",
          "Bee Coders | Tunis | Juil. - Oct. - 2023": "Bee Coders | Tunis | Juil. - Oct. - 2023",
          "Accueil": " Home",
          "Stages": "Internships",
          "Certificat": "Certificate",
          "Portfolio": "Portfolio",
          "Compétences": "Skills",
          "Adresse": "Address",
          "Déconnexion": "Log out",
          "Expérience professionnelle": "Professional experience",
          "Backend développé avec MongoDB et Node.js (Express.js). Frontend réalisé avec Next.js": "Backend developed with MongoDB and Node.js (Express.js). Frontend made with Next.js",
          "Changer la language": "choose a langage",
          "Formation et Certificats":"Training & Certificates",
          "Choisissez une langue":"Choose a language"

        },
        'ar_DZ': {
          "J'ai participé au club d'informatique NMTC, et ma participation est en cours jusqu'à présent. Portant les valeurs de sérieux et d'apprentissage, j'ai la ferme volonté de traduire mes acquisitions en résultats concrets, tout ce qui intéresse un ingénieur en développement.":
          'لقد شاركت في نادي الكمبيوتر NMTC، ومشاركتي جارية حتى الآن. حاملًا قيم الجدية والتعلم، لدي الرغبة القوية في ترجمة مكتسباتي إلى نتائج ملموسة، كل ما يهتم به مهندس التطوير.',
          'Téléphone : 20925959': 'الهاتف: 20925959',
          'Gmail : Nawreselou2382@gmail.com': 'جوجل : Nawreselou2382@gmail.com',
          'LinkedIn : linkedin.com/WearNawres': 'لينكد إن: linkedin.com/WearNawres',
          'Langages Manipulés :': 'اللغات المستخدمة:',
          'c, PHP, JavaScript, java, c#, python, ARDUINO, SGBD, PHP, JavaFx, react, next js 13, express.js, Django, .Net, Spring Boot Dax (Power BI), Flutter (Dart), Angular':
          'ج، PHP، جافا سكريبت، جافا، C#، بايثون، أردوينو، قواعد البيانات، PHP، JavaFx، رد فعل، next js 13، express.js، Django، .Net، Spring Boot Dax (Power BI)، Flutter (Dart)، Angular',
          'Logiciels Utilisés :': 'البرامج المستخدمة:',
          'ISIS, CodeBlocks, Brackets, MATLAB, Visual Studio, Power BI Desktop, Eclipse, WampServer, Studio 3T, MongoDB, Intellij IDEA, XAMPP, Android Studio, STS': 'ISIS، CodeBlocks، Brackets، MATLAB، Visual Studio، Power BI Desktop، Eclipse، WampServer، Studio 3T، MongoDB، Intellij IDEA، XAMPP، Android Studio، STS',
          "2023 - Spring Boot Certificate": '2023 - شهادة Spring Boot',
          "2022 - Azure Fundamentals certificate": '2022 - شهادة Azure Fundamentals',
          '2022 - Azure Devops certificate': '2022 - شهادة Azure Devops',
          '2022 - Azure WebApps certificate': '2022 - شهادة Azure WebApps',
          '2022 - AI Services In Azure certificate': '2022 - شهادة خدمات الذكاء الاصطناعي في Azure',
          '2022 - Big Data certificate': '2022 - شهادة Big Data',
          '2022 - Power BI certificate': '2022 - شهادة Power BI',
          '2022 - Intelligence Artificial certificate': '2022 - شهادة الذكاء الاصطناعي',
          '2023 - Automarketing certificate': '2023 - شهادة التسويق الذاتي',
          '2023 - planification stratégique certificate': '2023 - شهادة التخطيط الاستراتيجي',
          'Adresse Professionnelle': 'العنوان المهني',
          'Paramétre': 'الإعدادات',
          'Choisissez une langue': 'اختر لغة',
          'Expérience en Projets': 'خبرة في المشاريع',
          'Développement de projet E-Commerce': 'تطوير مشروع التجارة الإلكترونية',
          "Collaboration avec l\\'équipe de stagiaires de SwiftCode. Backend développé avec MongoDB et Node.js (Express.js). Frontend réalisé avec React.": 'التعاون مع فريق المتدربين في SwiftCode. تم تطوير الجزء الخلفي مع MongoDB و Node.js (Express.js). تم إنشاء الواجهة الأمامية باستخدام React.',
          'Développement du projet de santé Montale': 'تطوير مشروع الصحة مونتال',
          "Accueil": " استقبال",
          "Stages": "التدريب",
          "Certificat": "شهادة",
          "Portfolio": "استثمارات",
          "Compétences": "المهارات",
          "Adresse": "عنوان",
          "Déconnexion": "الخروج",
          "Expérience professionnelle": "الخبرة المهنية",
          "Backend développé avec MongoDB et Node.js (Express.js). Frontend réalisé avec Next.js":"تم تطوير الواجهة الخلفية باستخدام MongoDB و Node .js (Express.js). الواجهة الأمامية مصنوعة من التالي.js next",
          "Bee Coders | Tunis | Juil. - Oct. - 2023":"مبرمجو النحل | تونس | يوليو - أكتوبر - 2023",
          "Stagiaire technicien":"فني متدرب",
          "Observation des machines présentant un dysfonctionnement pour trouver la source du problème, diagnostiquant ainsi rapidement les causes de la panne pour réparation.":"مراقبة الآلات المعطلة للعثور على مصدر المشكلة ، وبالتالي التشخيص السريع لأسباب الفشل في الإصلاح.",
          "Vérification du bon fonctionnement de Chaine Radio en prenant en charge les tests techniques et en corrigeant les problèmes rencontrés, assurant ainsi le bon déroulé de la production.":"التحقق من حسن سير عمل راديو Chaine من خلال تولي مسؤولية الاختبارات الفنية وتصحيح المشكلات التي تواجهها ، وبالتالي ضمان التشغيل السلس للإنتاج.",
          "Sfax | Janv. - 2022":"صفاقس | يناير - 2022",
          "Stagiaire technicien OACA":"متدرب فني OACA",
          "Cheffe de Project IT":"مدير مشروع تكنولوجيا المعلومات",
          "Expérience en Projets":"تجربة المشروع",
          "Formation et Certificats":"التدريب والشهادات",
          "Curriculum Vitae":"السيرة الذاتية",
          "SwiftCode | Sfax | Juil. – 2023":"سويفت كود | صفاقس | يوليو - 2023",
          "Développement de Site de société de photographie":"تطوير موقع شركة التصوير الفوتوغرافي",
          "Développement de projet E-commerce":"تطوير مشاريع التجارة الإلكترونية",
          "Travail sur le Backend et le frontend en utilisant sping boot et le Frontend Angular.":"العمل على الواجهة الخلفية والواجهة الأمامية باستخدام sping boot والواجهة الأمامية Angular",
          "Travail sur le backend et le frontend en utilisant Django.":"العمل على الواجهة الخلفية والواجهة الأمامية باستخدام Django.",
          "Backend développé avec MongoDB et Node.js (Express.js). Frontend réalisé avec Next.js.":"تم تطوير الواجهة الخلفية باستخدام MongoDB و Node .js (Express.js). الواجهة الأمامية مصنوعة من Next.js.",
          "Travail sur le backend avec Spring Boot, utilisation de STS, XAMPP, MySQL et Postman.":"اعمل على الواجهة الخلفية باستخدام Spring Boot ، باستخدام STS و XAMPP و MySQL وساعي البريد.",
          '2023 - Certificat Spring Boot':'2023 - شهادة Spring Boot',
          '2022 - Certificat Azure Fundamentals':"2022 - شهادة أساسيات Azure",
          '2022 - Certificat Azure Devops':"2022 - شهادة Azure Devops",
          '2022 - Certificat Azure WebApps':"2022 - شهادة تطبيقات ويب Azure",
          '2022 - Certificat AI Services In Azure':"2022 - خدمات الذكاء الاصطناعي في شهادة Azure",
          '2022 - Certificat Big Data':"2022 - شهادة البيانات الضخمة",
          '2022 - Certificat Power BI':"2022 - شهادة Power BI",
          '2022 - Certificat Intelligence Artificial':"2022 - شهادة الذكاء الاصطناعي",
          '2023 - Certificat Automarketing':"2023 - شهادة التسويق التلقائي",
          '2023 - Certificat du planification stratégique':"2023 - شهادة التخطيط الاستراتيجي",
          "Choisissez une langue":'اختر لغة',
        },
      };
}